---
- name: Deploy Nginx Web Server
  hosts: web_servers
  become: yes
  vars:
    nginx_package: nginx
    nginx_service: nginx

  tasks:

    - name: Ensure Nginx is installed
      apt:
        name: "{{ nginx_package }}"
        state: present
        update_cache: yes
      tags: nginx

    - name: Start and enable Nginx service
      systemd:
        name: "{{ nginx_service }}"
        state: started
        enabled: true
      tags: nginx

    - name: Ensure Nginx is listening on port 80
      lineinfile:
        path: /etc/nginx/sites-available/default
        regexp: "listen 80 default_server;"
        line: "listen 80 default_server;"
      notify: Restart nginx
      tags: nginx

  handlers:
    - name: Restart nginx
      systemd:
        name: "{{ nginx_service }}"
        state: restarted